repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: 'https://github.com/jumanjihouse/pre-commit-hooks'
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: script-must-have-extension
      - id: git-dirty
      - id: git-check
        files: ^(.gitignore|README.md|CHANGELOG.md|CONTRIBUTING.md|LICENSE|LICENSE.md|LICENSE.txt|LICENSE.rst|LICENSE.html|LICENSE.htm|LICENSE.markdown|LICENSE.mdown|LICENSE.mkdn|LICENSE.mdwn|LICENSE.mdown|LICENSE.text|LICENSE.TXT|LICENSE.RST|LICENSE.HTML|LICENSE.HTM|LICENSE.MARKDOWN|LICENSE.MDOWN|LICENSE.MKDN|LICENSE.MDWN|LICENSE.MDOWN|LICENSE.TEXT|LICENSE)
