{
 "title": "java-tron-server",
 "description": "Monitor your java-tron server with Prometheus and Grafana.",
 "tags": [ "java-tron" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "6s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "gauge",
   "description": "Start time of the  java-tron process since unix epoch in seconds.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{group=`$group`,instance=`$instance`}* 1000"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "gauge",
   "description": "Up Time is a measure of system reliability, expressed as the percentage of time java-tron process, has been working and available",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{group=`$group`,instance=`$instance`}"
    }
   ]
  },
  {
   "title": "Header Height",
   "type": "stat",
   "description": "The latest block height of java-tron on this node.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tron:header_height{group=`$group`,instance=`$instance`}",
     "legendFormat": "Header height"
    }
   ]
  },
  {
   "title": "Header Time",
   "type": "stat",
   "description": "The latest block time of java-tron on this node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tron:header_time{group=`$group`,instance=`$instance`}",
     "legendFormat": "Header height"
    }
   ]
  },
  {
   "title": "SR Total Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tron:miner_total{instance=\"$instance\",type=\"success\"} ",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPUS",
     "type": "stat",
     "description": "The number of processors available to the java virtual machine.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_available_cpus{group=`$group`,instance=`$instance`}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "description": "Total: total physical memory.\n\nFree: free physical memory.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_total_physical_memory_bytes{group=`$group`,instance=`$instance`}",
       "legendFormat": "Total"
      },
      {
       "expr": "system_free_physical_memory_bytes{group=`$group`,instance=`$instance`}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "description": "The system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "system_load_average{group=`$group`,instance=`$instance`}",
       "legendFormat": "load average"
      }
     ]
    },
    {
     "title": "Open Fds",
     "type": "stat",
     "description": "Max: maximum number of open file descriptors. \n\nCurrent: number of open file descriptors.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_max_fds{group=`$group`,instance=`$instance`}",
       "legendFormat": "Max"
      },
      {
       "expr": "process_open_fds{group=`$group`,instance=`$instance`}",
       "legendFormat": "Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Txs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Pool",
     "type": "timeseries",
     "description": "Waiting for packed tansactions, including pending and repush.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "targets": [
      {
       "expr": "sum(tron:manager_queue_size{group=`$group`,instance=`$instance`,type !=`popped`,type !=`queued`})",
       "legendFormat": "pending pool"
      }
     ]
    },
    {
     "title": "Transaction Process Latency",
     "type": "timeseries",
     "description": "Average transaction processing time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "group by(contract) (rate(tron:process_transaction_latency_seconds_sum{type=\"block\"}[$__rate_interval])) / group by(contract) (rate(tron:process_transaction_latency_seconds_count{type=\"block\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Transaction TPS",
     "type": "timeseries",
     "description": "Average transaction TPS from broadcasted transactions,  not from blocks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 416 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tron:process_transaction_latency_seconds_count{group=\"$group\", instance=\"$instance\", type!=\"block\"}[$__interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(tron:process_transaction_latency_seconds_count{group=\"$group\", instance=\"$instance\", type!=\"block\"}[$__interval])",
       "legendFormat": "{{contract}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Generate Latency",
     "type": "timeseries",
     "description": "Average block generate time .",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "  rate(tron:block_generate_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])\n/\n  rate(tron:block_generate_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tron:block_generate_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "Block Process Latency",
     "type": "timeseries",
     "description": "Average block processing time when is not catching up.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "  rate(tron:block_process_latency_seconds_sum{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])\n/\n  rate(tron:block_process_latency_seconds_count{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tron:block_process_latency_seconds_bucket{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])) by (le))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "Block Process Latency From Sync",
     "type": "timeseries",
     "description": "Average block processing time when is not catching up.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "  rate(tron:block_process_latency_seconds_sum{group=`$group`,instance=`$instance`,sync =\"true\"}[$__interval])\n/\n  rate(tron:block_process_latency_seconds_count{group=`$group`,instance=`$instance`,sync =\"true\"}[$__interval])",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tron:block_process_latency_seconds_bucket{group=`$group`,instance=`$instance`,sync =\"true\"}[$__interval])) by (le))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "Verify Transactions Signature Latency",
     "type": "timeseries",
     "description": "Average  parallel verification transactions signature processing time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "  rate(tron:verify_sign_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])\n/\n  rate(tron:verify_sign_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tron:verify_sign_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "Block Push Latency ",
     "type": "timeseries",
     "description": "Average block processing time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tron:block_push_latency_seconds_sum{group=\"$group\", instance=\"$instance\"}[$__interval]) / rate(tron:block_push_latency_seconds_count{group=\"$group\", instance=\"$instance\", sync=\"true\"}[$__interval])",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(tron:block_push_latency_seconds_bucket{group=\"$group\", instance=\"$instance\"}[$__interval])))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "Block Push Lock Acquire Latency",
     "type": "timeseries",
     "description": "When handling the above block push logic, Tron's processing logic needs to acquire a synchronized lock. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tron:lock_acquire_latency_seconds_sum{group=\"$group\", instance=\"$instance\"}[$__interval]) / rate(tron:lock_acquire_latency_seconds_count{group=\"$group\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(tron:lock_acquire_latency_seconds_bucket{group=\"$group\", instance=\"$instance\"}[$__interval])))",
       "legendFormat": "tp99"
      }
     ]
    },
    {
     "title": "P95 / P99 Block Transaction Count",
     "type": "timeseries",
     "description": "95th percentile of transaction count per block.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(tron:block_transaction_count_bucket{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "P95 {{miner}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(tron:block_transaction_count_bucket{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "P99 {{miner}}"
      }
     ]
    },
    {
     "title": "Avg Transactions per Block",
     "type": "timeseries",
     "description": "Average number of transactions per block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(tron:block_transaction_count_sum{group=`$group`,instance=`$instance`}[$__interval]) / rate(tron:block_transaction_count_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{miner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SR Set",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "SR Set Change Events",
     "type": "table",
     "description": "Table of SR set change events showing additions and removals.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "tron:sr_set_change_total{group=`$group`,instance=`$instance`}"
      }
     ]
    },
    {
     "title": "SR Set Change Total",
     "type": "stat",
     "description": "Cumulative count of SR additions and removals.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tron:sr_set_change_total{group=`$group`,instance=`$instance`,action=\"add\"}) or vector(0)",
       "legendFormat": "SR Added"
      },
      {
       "expr": "sum(tron:sr_set_change_total{group=`$group`,instance=`$instance`,action=\"remove\"}) or vector(0)",
       "legendFormat": "SR Removed"
      }
     ]
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Peers",
   "type": "gauge",
   "description": "Node peers Info.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tron:peers{group=`$group`,instance=`$instance`}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Traffic /1 Minute",
   "type": "timeseries",
   "description": "Http network data traffic statistics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(tron:http_bytes_sum{group=\"$group\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{url}}.{{status}}"
    }
   ]
  },
  {
   "title": "Peers Abnormal/1min",
   "type": "gauge",
   "description": "Node abnormal peers statstics during past 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(tron:p2p_disconnect_total[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "UDP Traffic/s",
   "type": "timeseries",
   "description": "UDP network data traffic statistics rate over the past 30 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(tron:udp_bytes_sum{group=`$group`,instance=`$instance`}[$__interval])",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "TCP Traffic Rate/s",
   "type": "timeseries",
   "description": "TCP network data traffic statistics, average TCP bytes per second over the past 30 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tron:tcp_bytes_sum[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message Lantency > 50ms",
   "type": "timeseries",
   "description": "The average time to process a message received from a peer, when the message processing time exceeds 50ms, will be logged by the below metric. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(tron:message_process_latency_seconds_sum{group=\"$group\"}[$__interval])/ rate(tron:message_process_latency_seconds_count{group=\"$group\", instance=\"$instance\"}[$__interval])\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(tron:message_process_latency_seconds_bucket{group=\"$group\", instance=\"$instance\"}[$__interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": " HTTP QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum(rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tron:http_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])/rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": " GRPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "sum(rate(tron:grpc_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(tron:grpc_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "GRPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tron:grpc_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])/rate(tron:grpc_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"block\"})",
       "legendFormat": "block"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"block\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "transactionRetStore",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"transactionRetStore\"})",
       "legendFormat": "transactionRetStore"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"transactionRetStore\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "trans",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"trans\"})",
       "legendFormat": "trans"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"trans\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "transactionHistoryStore",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"transactionHistoryStore\"})",
       "legendFormat": "transactionHistoryStore"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"transactionHistoryStore\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "storage-row",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"storage-row\"})",
       "legendFormat": "storage-row"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"storage-row\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "account",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"account\"})",
       "legendFormat": "account"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"account\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "delegation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"delegation\"})",
       "legendFormat": "delegation"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"delegation\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "block-index",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"block-index\"})",
       "legendFormat": "block-index"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"block-index\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_join(jvm_info{group=\"$group\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "Memory Usage Rate ",
     "type": "timeseries",
     "description": "JVM heap used /  JVM heap init.\nJVM heap used /  JVM heap max.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{group=`$group`,instance=`$instance`})/sum(jvm_memory_bytes_init{group=`$group`,instance=`$instance`})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{group=`$group`,instance=`$instance`})/sum(jvm_memory_bytes_max{group=`$group`,instance=`$instance`})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "description": "JVM heap detail.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{group=`$group`,instance=`$instance`,area=\"heap\"}",
       "legendFormat": "{{area}}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{group=`$group`,instance=`$instance`}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "GC Time/Minute",
     "type": "timeseries",
     "description": "GC time every minute.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{group=\"$group\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Count/Minute",
     "type": "timeseries",
     "description": "GC count every minute.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{group=\"$group\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}