{
 "title": "java-tron-mechanism",
 "tags": [ "java-tron" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({group=\"$group\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Miner Success/H",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tron:miner_total{instance=\"$instance\",type=\"success\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Miss /6s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(increase(tron:miner_total{instance=\"$instance\",type=\"miss\"}[$__interval]))",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase (tron:miner_total{instance=\"$instance\",type=\"miss\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner Latency/10min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(tron:miner_latency_seconds_sum{instance=\"$instance\"}[$__interval])/increase(tron:miner_latency_seconds_count{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Vote-no data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tron:miner_g{instance=\"$instance\",type=\"vote\"}",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Miner (new or del)-no data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tron:miner_total{instance=\"$instance\",type=\"new\"}",
     "legendFormat": "new-{{miner}}"
    },
    {
     "expr": "tron:miner_total{instance=\"solidity86\",type=\"del\"}",
     "legendFormat": "del-{{miner}}"
    }
   ]
  },
  {
   "title": "Proposal-no data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "tron:proposal_g{instance=\"$instance\",type=\"vote\"}",
     "legendFormat": "{{miner}}"
    }
   ]
  }
 ]
}