global:
  scrape_interval: 6s
  scrape_timeout: 4s
  evaluation_interval: 6s
  external_labels:
    monitor: 'java-tron-node1-remote-write' # the external label is used to identify the Prometheus instance in the Thanos Querier UI


scrape_configs:
  - job_name: java-tron
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - tron-node1:9527
        labels:
          group: group-tron
          instance: fullnode-01
      - targets:
          - node-exporter:9100
        labels:
          group: node-exporter-full
          instance: fullnode-01

# The remote_write configuration tells Prometheus to continuously write metrics to the Thanos Receive service.
# Refer https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
remote_write:
  - url: http://thanos-receive:10908/api/v1/receive # if Thanos Receive service run on the same host with Prometheus
    headers:
      X-Service-Group: "tron-fullnode-group1"
    remote_timeout: 9s
    queue_config:
      capacity: 3000
      max_shards: 10 # the maximum number of shards, or parallelism, Prometheus will use for each remote-write queue
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 6s
      min_backoff: 3000ms
      sample_age_limit: 10s  # The maximum age of samples to send. This value must be greater than the scrape interval and batch_send_deadline.
      retry_on_http_429: false  # Drop requests when receiving an HTTP 429 (Too Many Requests) status code
    metadata_config:
      send: true
      send_interval: 120s # How frequently metric metadata is sent to remote storage.
      max_samples_per_send: 1000
