version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:12.4.1
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 2g
    environment:
      - GF_METRICS_ENABLED=true  # Enable Grafana metrics exposure
      - GF_SERVER_HTTP_PORT=3000  # Set Grafana's internal port to 3000
    volumes:
      - ../grafana_data:/var/lib/grafana  # Grafana database and dashboards
    ports:
      - "3000:3000"
    restart: unless-stopped
