version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - "9090:9090" # used for local query metrics
    volumes:
      - ../conf:/etc/prometheus
      - ../prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-remote-write.yml" # the default path to the configuration file
      - "--storage.tsdb.path=/prometheus" # the path where Prometheus stores its metric database
      - "--storage.tsdb.retention.time=7d" # takes about 2GB of disk space per week
      - "--storage.tsdb.max-block-duration=30m" #the maximum duration for a block of time series data that can be stored in the time series database (TSDB)
      - "--web.enable-lifecycle" # tell Prometheus to expose the /-/reload HTTP endpoints
      - "--web.enable-admin-api"
    restart: unless-stopped
